### ISSUE TITLE
gt.gtfcount error in 1.7.1

### ISSUE THREAD

**Issue by biounix** [gemtools/gemtools#14]
When running the RNA-pipeline with the precompiled static version of gemtools 1.7.1-i3, some of the jobs finish well whereas other end prematurely with an error from 'gt.gtfcount' (see below) and
filtered output files are not generated. After launching the pipeline again with the same set of files, the error appeared again but in different files. Same batch of files worked fine with version 1.7

Error log:
###### 

.
.
.
Running step: filtered
Step filtered finished in : 0:01:40
Running step: filtered.counts
2014-11-28 01:53:37,909 ERROR: Process '/apps/DEVEL/gemtools/1.7.1/bin/gt.gtfcount' finished with 1
Traceback (most recent call last):
  File "dist/build/pyi.linux2/gemtools/out00-PYZ.pyz/gem.pipeline", line 1482, in run
  File "dist/build/pyi.linux2/gemtools/out00-PYZ.pyz/gem.pipeline", line 320, in run
  File "dist/build/pyi.linux2/gemtools/out00-PYZ.pyz/gem", line 1089, in gtfcounts
ValueError: Error while running gt.gtfcounts
ERROR: Error while executing step filtered.counts : Error while running gt.gtfcounts
Cleaning up after failed step : filtered.counts
Step filtered.counts failed after : 0:00:10

gzip: stdout: Broken pipe
###### 

If more information can be of help just let me know, please.

Thank you.

**Comment by gresteban** [comment]
When run alone over a set of test BAM files, gt.gtfcout ends unexpectedly at random with the error:

System.Error::Signal raised (no=11)
