### ISSUE TITLE
Install fails with "name 'sys_platform is not defined'"

### ISSUE THREAD

**Issue by rcortini** [gemtools/gemtools#22]
Dear gemtools developers,
I am trying to install gemtools both from pip and from cloning from github. Both give me this error:
```
$ python setup.py install --user
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.49.tar.gz
Extracting in /tmp/tmpDVCVWN
Now working in /tmp/tmpDVCVWN/distribute-0.6.49
Building a Distribute egg in /home/rcortini/soft/gemtools
Traceback (most recent call last):
  File "setup.py", line 232, in <module>
    scripts = scripts,
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/tmpDVCVWN/distribute-0.6.49/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/tmp/tmpDVCVWN/distribute-0.6.49/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/tmp/tmpDVCVWN/distribute-0.6.49/pkg_resources.py", line 2099, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/tmp/tmpDVCVWN/distribute-0.6.49/pkg_resources.py", line 2309, in requires
    dm = self._dep_map
  File "/tmp/tmpDVCVWN/distribute-0.6.49/pkg_resources.py", line 2538, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/tmp/tmpDVCVWN/distribute-0.6.49/pkg_resources.py", line 2571, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/tmp/tmpDVCVWN/distribute-0.6.49/pkg_resources.py", line 2568, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/tmp/tmpDVCVWN/distribute-0.6.49/_markerlib/markers.py", line 109, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'sys_platform' is not defined
/home/rcortini/soft/gemtools/distribute-0.6.49-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    use_setuptools()
  File "/home/rcortini/soft/gemtools/distribute_setup.py", line 152, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/rcortini/soft/gemtools/distribute_setup.py", line 132, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "/home/rcortini/soft/gemtools/distribute_setup.py", line 123, in _build_egg
    raise IOError('Could not build the egg.')
IOError: Could not build the egg.
```
How can this error be solved?

**Comment by Poshi** [comment]
Try installing setuptools and uninstalling distribute before (if it is
installed). distribute is now part of setuptools:
$ pip uninstall distribute
$ pip install setuptools


--
Jordi Camps
jcamps@gmail.com

-----BEGIN GEEK CODE BLOCK-----
Version: 3.12
GCS/IT/S d-(+) s: a C++ UL++++() P+ L+(++) E- W++ N o? K? w++ !O M V
PS++ PE- Y? PGP t 5 X R(+) tv(+) b+ DI+ D+ G e+++ h r(--) y+**
------END GEEK CODE BLOCK------

2016-02-01 17:16 GMT+01:00 Ruggero Cortini <notifications@github.com>:

**Comment by rcortini** [comment]
I already tried this, it continues to fail

**Comment by Poshi** [comment]
I have no idea why it is trying to install distribute if setuptools is
installed. Which versions are you running of python and pip? Upgraded ones?
You can also try:
pip install --upgrade setuptools
pip install --upgrade pip

And if nothing works, try to install distribute per se, and once this is up
and running pyjip should find it already installed and won't try to install
it again:
pip install distribute


--
Jordi Camps
jcamps@gmail.com

-----BEGIN GEEK CODE BLOCK-----
Version: 3.12
GCS/IT/S d-(+) s: a C++ UL++++() P+ L+(++) E- W++ N o? K? w++ !O M V
PS++ PE- Y? PGP t 5 X R(+) tv(+) b+ DI+ D+ G e+++ h r(--) y+**
------END GEEK CODE BLOCK------

2016-02-02 10:05 GMT+01:00 Ruggero Cortini <notifications@github.com>:

**Comment by rcortini** [comment]
I am running python 2.7.10 and pip 8.0.2
Nothing is working, the installer is still attempting to install its own version of distribute.

**Comment by rcortini** [comment]
I solved this issue by commenting the first two lines in setup.py

**Comment by Poshi** [comment]
Really? This will have to be reworked. Thanks for the feedback!

**Comment by apredeus** [comment]
This problem still persists. Thank you @rcortini for your advice!

**Comment by apredeus** [comment]
Furthermore, the trick with commenting the first two lines used to work, but doesn't anymore. With all the pre-requisites installed, it results in whole lot of undefined references to what seems to be gemtools own functions.

`gt_profiler.c:(.text+0x16): undefined reference to `gt_malloc_'
gt_profiler.c:(.text+0x36): undefined reference to `gt_malloc_'
gt_profiler.c:(.text+0x56): undefined reference to `gt_malloc_'
gt_profiler.c:(.text+0x84): undefined reference to `gt_malloc_'
gt_profiler.c:(.text+0xa4): undefined reference to `gt_malloc_'
../lib/libgemtools.a(gt_profiler.o):gt_profiler.c:(.text+0xc4): more undefined references to `gt_malloc_' follow
../lib/libgemtools.a(gt_profiler.o): In function `gt_profiler_exit':
gt_profiler.c:(.text+0xef): undefined reference to `gt_free'
gt_profiler.c:(.text+0xfe): undefined reference to `gt_free'
gt_profiler.c:(.text+0x10d): undefined reference to `gt_free'
gt_profiler.c:(.text+0x11c): undefined reference to `gt_free'
gt_profiler.c:(.text+0x12b): undefined reference to `gt_free'
`

**Comment by marcopasi** [comment]
I have the same issue with Python 2.7.13 and pip 9.0.1 on macosx 10.12.6.

**Comment by tendertime** [comment]
I have the same issue with Python 2.7.17 and pip 20.1 , setuptools 44.1.0 distribute 0.7.3 on ubuntu 18.04...
