### ISSUE TITLE
Error while executing step bam

### ISSUE THREAD

**Issue by vitorlimac2** [gemtools/gemtools#28]
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 21 (Twenty One)
Release:	21
Codename:	TwentyOne
Python 2.7.8
gemtools 1.7.1

~$ gemtools rna-pipeline --stats-json -i /storage/data/genomes/T.cruzi/tryCruBrener/triTrypDB-28_2014-09-16/gemtools/genome_clean.gem -a ../custom_annotation/complete.gtf -f ../../../reads/2016-03_illumina/trimming_trimgalore/Epi-Y-1_R1_val_1.fq ../../../reads/2016-03_illumina/trimming_trimgalore/Epi-Y-1_R2_val_2.fq -t 20 -q 33 --compress-all

Log:

[...]
Calculating max read length
Max read length: 75
Indexing denovo transcriptome
Step denovo-index finished in : 0:15:10
Running step: denovo-mapping
Step denovo-mapping finished in : 0:21:51
Running step: merge_and_pair
2017-09-08 13:25:26,369 : Disabeling stream compression
Step merge_and_pair finished in : 0:24:46
Running step: stats
Step stats finished in : 0:03:05
Running step: bam
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gem/pipeline.py", line 1482, in run
    step.run()
  File "/usr/lib64/python2.7/site-packages/gem/pipeline.py", line 342, in run
    gem.sam2bam(sam, self._final_output(), sorted=cfg["sort"], mapq=cfg["mapq"], threads=self.pipeline.threads, sort_memory=self.pipeline.sort_memory)
  File "/usr/lib64/python2.7/site-packages/gem/__init__.py", line 918, in sam2bam
    sam2bam_p = _check_samtools("view", threads=threads, extend=["-S", "-b"])
  File "/usr/lib64/python2.7/site-packages/gem/__init__.py", line 900, in _check_samtools
    (s, e) = subprocess.Popen([executables["samtools"], "view"], stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ERROR: Error while executing step bam : [Errno 2] No such file or directory
Cleaning up after failed step : bam
Step bam failed after : 0:00:00

**Comment by Poshi** [comment]
I bet you samtools executable is no in the $PATH. Try to run samtools from
the command line just by typing "samtools". If it does not work, this is
the problem.


--
Jordi Camps
jcamps@gmail.com

-----BEGIN GEEK CODE BLOCK-----
Version: 3.12
GCS/IT/S d-(+) s: a C++ UL++++() P+ L+(++) E- W++ N o? K? w++ !O M V
PS++ PE- Y? PGP t 5 X R(+) tv(+) b+ DI+ D+ G e+++ h r(--) y+**
------END GEEK CODE BLOCK------

2017-09-08 21:57 GMT+02:00 vitorlimac2 <notifications@github.com>:
